
 POST http://localhost:3000/todos
 Content-Type: application/json

 {
    "taskTitle": "mine alone",
    "taskDescription": "only my data",
    "userId": "65f02920c4f7eac061b30110"
}



###
 POST  http://localhost:3000/todos/signup
 Content-Type: application/json

 {
     "userName":"eeeeddd",
     "accessCode":"77777"
 }











 
 ###
 POST  http://localhost:3000/todos/signup
 Content-Type: application/json

 {
     "userName":"eeeeddd",
     "accessCode":"77777"
 }
